### for all tasks 
Get https://three41-week-3-4.onrender.com/users

### for a single task
Get https://three41-week-3-4.onrender.com/users/67db68fd2f31d775f9062704

### create user
Post https://three41-week-3-4.onrender.com/users
Content-Type: application/json

{
    "firstName": "Ray",
    "lastName": "Ruppe",
    "password": "thissimypasswords",
    "email": "ray.ruppe@gmail.com"
}

### update user
Put https://three41-week-3-4.onrender.com/users/67db68fd2f31d775f9062704
Content-Type: application/json

{
    "firstName": "Noah",
    "lastName": "Ruppe",
    "password": "GreatPassword",
    "email": "nick.ruppe1125@gmail.com"
}

### delete the user
Delete https://three41-week-3-4.onrender.com/users/67dcbadf89140ef9a69ba755






### test getting task userid
Get https://three41-week-3-4.onrender.com/tasks/67db68fd2f31d775f9062704

### get single task for user   taskid
Get https://three41-week-3-4.onrender.com/tasks/67dca22ae1593be37c9b4b63

### create a new task userid
POST  https://three41-week-3-4.onrender.com/tasks/67db68fd2f31d775f9062704
Content-Type: application/json

{
    "title": "reading assignment",
    "description": "to kill a mockingbird",
    "dueDate": "March 30, 2025",
    "progress": "woriking on it",
    "instructor": "rick james",
    "subject": "Reading"
}


### update the task userid/taskid
PUT https://three41-week-3-4.onrender.com/tasks/67db68fd2f31d775f9062704/67dca22ae1593be37c9b4b63
Content-Type: application/json

{
    "title": "Node project",
    "description": "this shows my skills in node",
    "dueDate": "March 22, 2025",
    "progress": "finished it.",
    "instructor": "jeremy lindsy",
    "subject": "node class"
}


### delete a task  userid/taskid
Delete  https://three41-week-3-4.onrender.com/tasks/67db68fd2f31d775f9062704/67dca22ae1593be37c9b4b63


