### for all tasks 
Get https://three41-week-3-4.onrender.com/users

### for a single task
Get https://three41-week-3-4.onrender.com/users/67db68fd2f31d775f9062704

### create user
Post https://three41-week-3-4.onrender.com/users
Content-Type: application/json

{
    "firstName": "Nick",
    "lastName": "Ruppe",
    "password": "thissimypasswords",
    "email": "Nick.ruppe@gmail.com"
}

### update user
Put https://three41-week-3-4.onrender.com/users/67db68fd2f31d775f9062704
Content-Type: application/json

{
    "firstName": "Noah",
    "lastName": "Ruppe",
    "password": "password1",
    "email": "noah.ruppe1125@gmail.com"
}

### delete the user
Delete https://three41-week-3-4.onrender.com/users/67de4087f445b8d557646ca7






### test getting task userid
Get https://three41-week-3-4.onrender.com/tasks/67db68fd2f31d775f9062704

### get single task for user   taskid
Get https://three41-week-3-4.onrender.com/tasks/67db68fd2f31d775f9062704/67dcba5265d31fd6e1aa181a

### create a new task userid
POST  https://three41-week-3-4.onrender.com/tasks/67db68fd2f31d775f9062704
Content-Type: application/json

{
    "title": "tagalog",
    "description": "How to speak tagalog",
    "dueDate": "March 30, 2025",
    "progress": "woriking on it",
    "instructor": "mick manners",
    "subject": "filipino"
}


### update the task userid/taskid
PUT https://three41-week-3-4.onrender.com/tasks/67db68fd2f31d775f9062704/67e48806f18fd5b212727385
Content-Type: application/json

{
    "title": "Node project",
    "description": "this shows my skills in node",
    "dueDate": "March 22, 2025",
    "progress": "finished1111q it.",
    "instructor": "jeremy lindsy",
    "subject": "node class"
}


### delete a task  userid/taskid
Delete  https://three41-week-3-4.onrender.com/tasks/67db68fd2f31d775f9062704/67de4246f445b8d557646cab


